### ISSUE TITLE
Caching does not honor SaveToken

### ISSUE THREAD

**Issue by cbeall** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#10]
When enabling both caching and SaveTokens, the first request adds the token to the authentication property items and saves info to the cache. A subsequent request (that leverages the cache) does not store the token in the authentication property items.

The behavior should be consistent whether or not the cache is being used. I'm not sure if it's better to read the saved token from the cache (which would need to be added), or to just pull the token from the request header. Either way would yield the same result, but the former would open up possibilities with reference token to JWT exchange (IdentityServer/IdentityServer4#507)

**Comment by leastprivilege** [comment]
PR?

**Comment by cbeall** [comment]
I'll have something by this weekend.
