### ISSUE TITLE
Caching claims for introspection encrypts the CacheKeyPrefix as well

### ISSUE THREAD

**Issue by RotemKir** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#111]
In OAuth2IntrospectionHandler when using the cache to get / set the claims of a token a cache key is created by adding a cache key prefix to the token:
`var key = $"{Options.CacheKeyPrefix}{token}";`

However, in the CacheExtensions that key is encrypted, making the cache key prefix useless:
`var bytes = await cache.GetAsync(token.Sha256()).ConfigureAwait(false);`

As we're using redis as a distributed cache this adds a lot of noise - a lot of keys with encrypted names in the root of the redis "tree". The prefix is critical when managing items in redis.

Can you encrypt only the token part of the cache key ?

**Comment by leastprivilege** [comment]
Sounds like a bug. I don't have the time right now to fix it. Feel free to propose a PR.

**Comment by RotemKir** [comment]
Added a PR:
#112

**Comment by RotemKir** [comment]
Hi, it's been 2 weeks since I posted the PR, any chance that it'll be approved ? Much appreciated.
