### ISSUE TITLE
Support for actor claim type

### ISSUE THREAD

**Issue by matiii** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#113]
Hi,

Could you provide similar support for actors as AddJwtBearer handler does ?

**Comment by leastprivilege** [comment]
I need more details.

**Comment by matiii** [comment]
Based on actort claim, lib should create Actor ClaimIdentity. Docs below
https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsidentity.actor?view=netcore-3.1
https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes.actor?view=netcore-3.1

**Comment by leastprivilege** [comment]
Hey, 

sorry this has been sitting here for a long time...

couple of questions - 

* where does the `actort` claim type come from - the closest I could think of is `act` from the token exchange spec
* your assumption seems to be that there is a JWT on that claim - who produces this?

thanks

**Comment by matiii** [comment]
Hi sorry, for late replying 

Ad.1 Yep, i think `act` is the closest to `actort`, however I suspect abbreavation means `actor token` 
Ad.2 I produce it on my custom grant type flow
