### ISSUE TITLE
Client ID and secret vs. scope

### ISSUE THREAD

**Issue by andrew-laughlin** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#12]
Thanks for putting this together. I have a couple of questions around usage.

1. Why are client ID and secret required? I was under the impression that resources authenticated to the introspection endpoint via scope ID and secret.

2. Is this middleware to be used in tandem with bearer token middleware (e.g. UseJwtBearerAuthentication) or as a replacement?

Thanks

**Comment by leastprivilege** [comment]
Well - from a MW point of view it is client id and secret. In IdentitySever don't call is scope secret anymore - but API secret.

It is meant as a replacement for the JWT bearer MW - if you need both - use 

https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation
