### ISSUE TITLE
Concurrency issue in OAuth2IntrospectionHandler - mixing up HttpContext

### ISSUE THREAD

**Issue by espenrl** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#128]
Whenever I see a concurrency issue I look for a `static`.

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/5053d30c0abdb2aecbd482e31abca8dbf81a2bfd/src/OAuth2IntrospectionHandler.cs#L28

Found one! Know let's see if it's code path handles `HttpContext` gracefully. This lambda should not use `HttpContext` in any way.

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/5053d30c0abdb2aecbd482e31abca8dbf81a2bfd/src/OAuth2IntrospectionHandler.cs#L111

It calls `CreateTicket`.

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/5053d30c0abdb2aecbd482e31abca8dbf81a2bfd/src/OAuth2IntrospectionHandler.cs#L130

Yep, it captures the `HttpContext` when creating `TokenValidatedContext` which is then cached in `IntrospectionDictionary`.

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/5053d30c0abdb2aecbd482e31abca8dbf81a2bfd/src/OAuth2IntrospectionHandler.cs#L189

**Comment by leastprivilege** [comment]
Thanks! What exactly was the problem?

**Comment by leastprivilege** [comment]
I looked at the PR - I like it. Just want to understand what the issue was in the first place.

**Comment by espenrl** [comment]
I experienced a weird issue. I have a middleware which adds another custom identity to the principal. No problem, has worked for many years.

When I switched from `IdentityServer4.AccessTokenValidation` (doesn't work on .NET 5) to `IdentityModel.AspNetCore.OAuth2Introspection` I started getting multiples of my custom identity on the same principal in the same HttpContext. Probably due to the nature of our apps loading multiple resources when loading the site (Angular) which triggers the `IntrospectionDictionary `.

The fix I did solved that issue.

**Comment by leastprivilege** [comment]
interesting.

**Comment by leastprivilege** [comment]
OK. Merged. Thanks!

**Comment by espenrl** [comment]
I guess the different requests ended up sharing the same principal object. Which would be bad.
