### ISSUE TITLE
map Claims like Microsoft.AspNetCore.Authentication.JwtBearer

### ISSUE THREAD

**Issue by Azaferany** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#148]
hi 
im using your great library as well as Microsoft.AspNetCore.Authentication.JwtBearer for Authentication
in in v5 JwtBearer  add a prop for change default behavior of maping in v5 [MapInboundClaims ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions.mapinboundclaims?view=aspnetcore-5.0#Microsoft_AspNetCore_Authentication_JwtBearer_JwtBearerOptions_MapInboundClaims) and its use this maping [maping](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d6f2b66d788195b50f2b1f700beb497851194c73/src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs#L41)

in the older version of jwt thay change type of jwt claim and your package not and in the dev of projects they use both of them its make  conflict 
i think its would be nice feature in your package

**Comment by leastprivilege** [comment]
You can do any mapping in extensibility like events or claims transformation. I think passing the real values on is the best behavior.
