### ISSUE TITLE
Token Cache  Issue

### ISSUE THREAD

**Issue by nanthakumar2007** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#151]
Below code having issue it's not considering actual token exp and its always considering with default cacheduration property value 
My token exp value is 20 mins but  every 5 mins  its requesting and verify with  introspection endpoint due to below code.

public TimeSpan CacheDuration { get; set; } = **TimeSpan.FromMinutes(5);**

// if the lifetime of the token is shorter than the duration, use the remaining token lifetime
            DateTimeOffset absoluteLifetime;
            if (expiration <= now.Add(**duration**))
            {
                absoluteLifetime = expiration;
            }
            else
            {
                **absoluteLifetime = now.Add(duration);**
            }

Could you please support user should use either exp (claim) or cacheduration property. currently system is forcing to set  cacheduration

**Comment by leastprivilege** [comment]
Yes - this is because someone could revoke the token before its expiration time. That's the whole point of using reference tokens.
