### ISSUE TITLE
Backchannel Http Client configuration does not have an example in documentation

### ISSUE THREAD

**Issue by rwkarg** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#162]
When setting up JWT support, we can specify that a proxy should be used to hit the Authority
```
.AddJwtBearer(options =>
            {
                options.BackchannelHttpHandler = new HttpClientHandler
                {
                    UseProxy = true,
                    Proxy = new WebProxy(WebProxyUri, true)
                };
            }
```

but there doesn't appear to be a similar mechanism to support this with `.AddOAuth2Introspection("introspection", options => {...}`

**Comment by rwkarg** [comment]
Looks like this is the method for configuring the backchannel HTTP handler
https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/bcb0d1741450307e43eba0b4ffbdd00acca079f8/test/Tests/Util/PipelineFactory.cs#L36-L40

**Comment by rwkarg** [comment]
Updated README.md with Backchannel HTTP Client configuration example in https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/pull/163

**Comment by leastprivilege** [comment]
yes - that's correct.

**Comment by leastprivilege** [comment]
thanks - i will merge your PR.
