### ISSUE TITLE
Where do claims from userinfo fit?  (OIDC, SPA and opaque access tokens)

### ISSUE THREAD

**Issue by wrschneider** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#169]
I have a similar question to #68:

I have a SPA doing OIDC (code + PKCE) on client side.  The browser gets an ID token and an access token.  
I need to get the email claim on the ASP.NET backend.
My IDP (in-house, not Identity Server or AAD) returns opaque access tokens, not JWT. 

OAuth2Introspection will validate the token via introspection but my particular IDP doesn't return all the claims I need.

I could use the userinfo endpoint to get other claims, but I'd like this to be built into AuthenticationBuilder somehow, and such that I can get the claims out of `User.Claims` in a controller class.

What I'm looking for is like a hybrid of OAuth2Introspection and AddOpenIdConnect.

If OAuth2Introspection isn't the right place for this, because userinfo is OIDC not OAuth, then what _is_ the right place?

**Comment by leastprivilege** [comment]
Using something else than `your particular IDP` maybe? ;)

The introspection endpoint is supposed to return the contents of the access token, if the required claim is not in the access token, then you need to retrieve it from *somewhere* else.

**Comment by wrschneider** [comment]
> Using something else than `your particular IDP` maybe? ;)
> 
> The introspection endpoint is supposed to return the contents of the access token, if the required claim is not in the access token, then you need to retrieve it from _somewhere_ else.

Yep, I can get what I need from userinfo endpoint, but what I want to clarify is -- 

- it would be wrong to add support for userinfo endpoint into OAuth2Introspection because userinfo is an OIDC concept, and we can't assume the access token was obtained through OIDC.  In other words, if I created a PR to call Userinfo here, it wouldn't get merged

- introspection endpoint is the right answer for this use case, and the IDP is broken for not returning the requested scopes (introspection shows "scope" includes "email" but does not return email claim) - or is it, because this specific claim is not required in the introspection response?

**Comment by leastprivilege** [comment]
> because userinfo is an OIDC concept, and we can't assume the access token was obtained through OIDC. In other words, if I created a PR to call Userinfo here, it wouldn't get merged

that is correct

> introspection endpoint is the right answer for this use case, and the IDP is broken for not returning the requested scopes (introspection shows "scope" includes "email" but does not return email claim)

yes.

**Comment by wrschneider** [comment]
> > because userinfo is an OIDC concept, and we can't assume the access token was obtained through OIDC. In other words, if I created a PR to call Userinfo here, it wouldn't get merged
> 
> that is correct

Hmm, it does look like OAuth2Introspection acknowledges OIDC in that it can use the OIDC discovery endpoint to get the introspection endpoint.  So it wouldn't be reasonable to allow for the userinfo endpoint as well?

**Comment by leastprivilege** [comment]
no. This is just a convenience I added.

There is also OAuth metadata which would serve the same purpose.

**Comment by leastprivilege** [comment]
But do whatever you need to do for your use case. You don't really need my blessing for that.

It's free software ;)
