### ISSUE TITLE
 Unauthorized status should be send WWW-Authenticate on header

### ISSUE THREAD

**Issue by fchiumeo** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#18]
Unauthenticated requests should return a response whose header contains a HTTP 401 Unauthorized status and a WWW-Authenticate field.

https://tools.ietf.org/html/rfc1945#section-10.16

**Comment by mozkarakoc** [comment]
Hi,

I sent a pull request about this issue. If the intospection response has a error message or error claim, handler try to add WWW-Authenticate header with error description.

@leastprivilege , @johnkors could you please review it?

**Comment by leastprivilege** [comment]
We just released 3.0.0 for ASP.NET Core 2 - 

we don't have the cycles to continue supporting the old version. If you want to re-consider this feature on top of the new architecture - let me know.

**Comment by fchiumeo** [comment]
please add to Net Core 2
i'm using .Net Core 2 in my application; until now I had the source code in my project
thanks

**Comment by leastprivilege** [comment]
do a PR if you want.
