### ISSUE TITLE
Full framework support

### ISSUE THREAD

**Issue by rmja** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#2]
When https://github.com/IdentityModel/IdentityModelv2/pull/2 is merged, the only requirement should be to add `net451` as a framework.

**Comment by leastprivilege** [comment]
I will work on that next week.

**Comment by leastprivilege** [comment]
i updated all the packages - give it a go and see if that works better for you (and open a new issue if you encounter problems)
