### ISSUE TITLE
Consider supporting different authentication methods

### ISSUE THREAD

**Issue by ycrumeyrolle** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#21]
The current implementation only support the client authentication method `client_secret_post`. 
The introspection endpoint may also support other methods: 
- `client_secret_basic`
- `client_secret_jwt`
- `private_key_jwt`

The discovery endpoint should be used for retrieving the following [metadata](https://tools.ietf.org/html/draft-ietf-oauth-discovery-07):  
- `introspection_endpoint_auth_methods_supported`
- `introspection_endpoint_auth_signing_alg_values_supported`

**Comment by leastprivilege** [comment]
True. Thats why there is support for custom HTTP handlers.

If you want to work on something more elaborate - let me know.
