### ISSUE TITLE
NameClaimType only works for either personal access token (sub) or client_id both not both

### ISSUE THREAD

**Issue by KasperHoldum** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#22]
Hello,

In our setup we have an API setup where it receives reference tokens from different sources. They can come from apps where users are logged in, or from scripts running with client credentials.

The claims are different in these two scenarios. In the first the identity is inside the 'sub' claim, and in the second they are inside the 'client_id' claim.

We are looking to map both of these to the name, but since the NameClaimType option only allows a single string this is not possible.

Are there are good ways around this?

**Comment by brockallen** [comment]
Claims transformation.

**Comment by KasperHoldum** [comment]
Claims transformation worked perfectly. For reference here is the solution I ended up with:
```
    public class ClientIdAndSubClaimsTransformation : IClaimsTransformation
    {
        public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
            var name = principal.Claims.SingleOrDefault(s => s.Type.ToLower() == "sub") ?? principal.Claims.SingleOrDefault(s => s.Type.ToLower() == "client_id");

            if (name != null && !principal.HasClaim(s => s.Type == "UserOrClientId"))
            {
                ((ClaimsIdentity)principal.Identity).AddClaim(new Claim("UserOrClientId", name.Value));
            }

            return Task.FromResult(principal);
        }
    }

            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(o =>
            {
                (...)
                o.NameClaimType = "UserOrClientId";
            });
```
