### ISSUE TITLE
Unauthorized status should be send WWW-Authenticate on header

### ISSUE THREAD

**Issue by ebrubulutt** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#25]
Please, retake this into consideration. we need to handle expired responses both jwt and instrospeciton handlers. #20 
Or you maybe consider add this feature #14

**Comment by leastprivilege** [comment]
for #20 - want to investigate and send a PR?

**Comment by leastprivilege** [comment]
PR or close?
