### ISSUE TITLE
Discovery endpoint retrieval problem

### ISSUE THREAD

**Issue by vladbondarenko1** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#26]
Hi. We have a problem with discovery document endpoint. 
**Steps:**

1. Stop the IdentityProvider site.
2. Start application which use IdentityProvider authentication
3. Make a request to application
4. Start the IdentityProvider site.
5. Make the request again

**Expected result**
Step 3 fails with
`System.InvalidOperationException: Error parsing discovery document from http://localhost:9090/.well-known/openid-configuration: Error connecting to http://localhost:9090/.well-known/openid-configuration: An error occurred while sending the request.
   at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.<GetIntrospectionEndpointFromDiscoveryDocument>d__3.MoveNext()`

Step 5 succeeds, because IdentityServer is up and running again and metadata can be retrieved.

**Actual result:**
All subsequent requests fail with the same exception. There is no retry behavior for retrieving discovery endpoint metadata, only restart application can help.

Screenshoot with error:
![1](https://user-images.githubusercontent.com/26981150/36155099-1f7b3e6e-10dc-11e8-9370-8c2f9475e3af.png)
![3](https://user-images.githubusercontent.com/26981150/36156209-084630c0-10df-11e8-8179-21e9f17cdd6e.png)

IdentityServer authentication settings:
![2](https://user-images.githubusercontent.com/26981150/36155964-7569f732-10de-11e8-85fd-6a29ca0c050a.png)

**Comment by leastprivilege** [comment]
Thanks for reporting. That's indeed not the right behavior.

We are looking into this - but this might take some time. Feel free to work on a fix and PR yourself.

**Comment by profet23** [comment]
Also seeing this behavior.

**Comment by profet23** [comment]
Pull request submitted: #29

**Comment by RafaelHarder** [comment]
I'm also having problems with this. =/ What about that PR with the proposed solution? Looks good to me.

**Comment by profet23** [comment]
Any update on this? During initial deployments we seem to run into this bug pretty often.

**Comment by leastprivilege** [comment]
I merged the PR - will push a new nuget ASAP.

**Comment by leastprivilege** [comment]
thanks!

**Comment by gekkedev** [comment]
Is this issue considered fixed?
```
PDL:00000001": An unhandled exception was thrown by the application.
very document from https://mydomain.net/auth/.well-known/openid-configuration: Error connecting to https://mydomain.net/auth/.well-known/openid-c
onfigureOAuth2IntrospectionOptions.<GetIntrospectionEndpointFromDiscoveryDocument>d__3.MoveNext()
xception was thrown ---
Info.Throw()
NonSuccessAndDebuggerNotification(Task task)
onfigureOAuth2IntrospectionOptions.<InitializeIntrospectionClient>d__4.MoveNext()
xception was thrown ---
Info.Throw()
NonSuccessAndDebuggerNotification(Task task)
2IntrospectionHandler.<LoadClaimsForToken>d__5.MoveNext()
xception was thrown ---
Info.Throw()
NonSuccessAndDebuggerNotification(Task task)
2IntrospectionHandler.<HandleAuthenticateAsync>d__3.MoveNext()
xception was thrown ---
Info.Throw()
NonSuccessAndDebuggerNotification(Task task)
Handler`1.<AuthenticateAsync>d__47.MoveNext()
xception was thrown ---
Info.Throw()
NonSuccessAndDebuggerNotification(Task task)
Service.<AuthenticateAsync>d__10.MoveNext()
xception was thrown ---
Info.Throw()
NonSuccessAndDebuggerNotification(Task task)
erAuthenticationHandler.<HandleAuthenticateAsync>d__2.MoveNext()
xception was thrown ---
Info.Throw()
NonSuccessAndDebuggerNotification(Task task)
Handler`1.<AuthenticateAsync>d__47.MoveNext()
...skipping...
```

**Comment by leastprivilege** [comment]
yes
