### ISSUE TITLE
Support adding custom claims to the cache

### ISSUE THREAD

**Issue by garyarcher36** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#28]
Hi guys - as always, a really good library that is easy to integrate. I have a request that I believe would improve your library further, and is a feature my company will want to use.

**CLAIMS USED BY APIs**
Many APIs use claims from a number of sources to enforce business level authorization and it can be highly useful in some scenarios to cache all of these when first validating a token:
* Token claims
* Extra user info claims
* Extra data points used for authorization on every single API request

**PROPOSED SOLUTION**
I would like to extend OAuth2IntrospectionOptions with a new optional property that looks like this:

```
public async <UGLYFUNCTION_TYPE> ExtraClaimsRetriever { get; set; }

/*
 * Typical usage is to get the user id from the token, then make a remote call to get extra claims
 */
public IEnumerable<Claim> async GetExtraClaims(IEnumerable<Claim> tokenClaims, string accessToken)
{
    string userId = tokenClaims.Single(c => c.Type == "sub");
    var extraData = await authorizationMicroService.GetUserBusinessRights(userId, accessToken);
    return new List<Claim>(DataToClaims(extraData);
}
```

**FURTHER BACKGROUND**
My company uses a claims caching solution documented [here](http://authguidance.com/2017/10/03/api-tokens-claims#api-claims-cache) in an OAuth tutorial based blog I am writing. We would like to update some APIs to .Net Core soon and would like to use your library to manage introspection and claims caching.

**NEXT STEPS**
I'd like to see if you agree with this as a feature. If it helps I'd be happy to code a pull request. Very interested in your thoughts on any of this.

Regards, Gary

**OUT OF INTEREST**
I also wrote a [Code Sample with a .Net Core API called by an SPA](https://github.com/garyarcher36/authguidance.websample.netcoreapi) and your library worked very nicely, except that I can't quite get the claims caching I want.

**Comment by garyarcher36** [comment]
OK Dominick - that's a perfectly reasonable answer and should work well.

The reason I asked is because we have some verbose data related to user roles that we don't want to put in access tokens:

* So in each API we do a lookup and then cache these claims for the **access token lifetime**
* We want the key of the cached item to be the **hash of the access token**

The above characteristics are the same as your cache implementation.

If a user is running a UI that interacts with 3 APIs, and the user's role has been changed by an administrator, the user can log off and on again. All 3 APIs will then receive a new access token and will use updated roles in their authorization.

I should easily be able to achieve these goals via a second cache middleware, that runs after introspection, as you suggest. I'll need a second cache instance and can just duplicate a little code out of your [CacheExtensions class](https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/dev/src/IdentityModel.AspNetCore.OAuth2Introspection/Infrastructure/CacheExtensions.cs)

Feel free to close this in the meantime - and thanks for the answer.

**Comment by leastprivilege** [comment]
You can also configure IdentityServer to include a unique ID (jti) in the access token - you could use this instead for your cache key.
