### ISSUE TITLE
Possible deadlock in OAuth2IntrospectionMiddleware

### ISSUE THREAD

**Issue by ChrisBellew** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#3]
I believe I've uncovered a possible deadlock scenario that can occur in `OAuth2IntrospectionMiddleware` under heavy load.

If I bombard the server with many requests I can quite reliably force it to enter a deadlock where one thread is stuck in...

`IdentityModel.AspNetCore.OAuth2Introspection.dll!IdentityModel.AspNetCore.OAuth2Introspection.AsyncHelper.RunSync<string>`

and another 2,000+ threads are stuck in...

`IdentityModel.AspNetCore.OAuth2Introspection.dll!IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionMiddleware.CreateHandler`

...and I've left it over the weekend and it doesn't resolve itself. 

I think the problem is using a `System.Task` inside the lazy initialiser for `System.Lazy<IntrospectionClient>`.

`System.Lazy` uses locks in its implementation and this can cause deadlocks if you use a task inside its initialiser. See this quote from the `System.Lazy` documentation...

"In certain situations, you might want to avoid the overhead of the `Lazy<T>` object's default locking behavior. In rare situations, there might be a potential for deadlocks."
https://msdn.microsoft.com/en-us/library/dd642331(v=vs.110).aspx

...and this quote from Eric Lippert...

"Awaiting inside a lock is a recipe for producing deadlocks."
http://stackoverflow.com/questions/7612602/why-cant-i-use-the-await-operator-within-the-body-of-a-lock-statement

I actually just worked around this issue twice in my own code before running into this issue, so I know this is a problem.

I would be grateful if someone could look into this for me. 

Thanks in advance.
Chris

**Comment by brockallen** [comment]
> In rare situations, there might be a potential for deadlocks.

Yea, that's an awfully disconcerting, yet off-handed comment. It makes one wonder if it should ever be used. 

In any event, we'll look into it. Thanks.

**Comment by leastprivilege** [comment]
thanks! how would you resolved that issue (given you already did that for your own code).

**Comment by ChrisBellew** [comment]
I removed the System.Lazy and instead used a SemaphoreSlim to ensure only
one thread was initialising the resource at once.

**Comment by leastprivilege** [comment]
Could that be a solution?

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/104

**Comment by ChrisBellew** [comment]
Yes, that seems like it would work.

It's probably not the exact intended use of `System.Lazy`, but it will avoid the lock and therefore the deadlock. So I'm happy!

**Comment by leastprivilege** [comment]
So can you give it a try with your test harness?

**Comment by leastprivilege** [comment]
Can you - or should I make the change myself and publish to myget. Will you then test it?

**Comment by ChrisBellew** [comment]
Actually, the link to the proposed solution is for a different repository and I don't see how it helps this repository.

Regardless, I can see the same solution could be made to this repository so I did the following...

I tried the LazyThreadSafetyMode.ExecutionAndPublication and found that it is not an ideal solution. While it doesn't lock- and therefore avoids the deadlock - it means many threads can run the initialiser which causes many needless duplicate HTTP requests to .well-known/openid-configuration. 

The solution I have gone with is to use a non-locking lazy that I made specifically, which ensures only one thread is running the initialiser but doesn't use a lock to do so. I have tested that this eliminates the deadlock by temporarily copying and pasting this projects code into my own codebase. Would you be happy to accept this a solution to this project if I did a pull request?

Further, I have added ConfigureAwait(false) to all awaits in the code that I copied and pasted to remove more potential deadlock situations and remove needless thread queuing for continuations. My understanding is that there is strong consensus in the wider community that unless you are awaiting from UI thread, you should always use ConfigureAwait(false). Would you be happy to accept this in the PR as well?

Thanks

**Comment by leastprivilege** [comment]
Yes please send a PR - I want to have a look at it. Thanks!

**Comment by ChrisBellew** [comment]
I'll get back to you shortly then

**Comment by brockallen** [comment]
Merged.
