### ISSUE TITLE
Make TokenTypeHint configurable by adding it to the OAuth2IntrospectionOptions class

### ISSUE THREAD

**Issue by mikaelstrid** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#30]
**Background**
We are integrating with the "WSO2 Identity & Access Management" product (https://wso2.com/identity-and-access-management) but it doesn't handle receiving an unexpected token type hint in the introspection call even though the RFC 7662 (https://tools.ietf.org/html/draft-ietf-oauth-introspection-11) chapter 2.1 clearly states that it should.

The consequence is that since IdentityModel.AspNetCore.OAuth2Introspection always sends "token_type_hint=access_token" in the OAuth2IntrospectionHandler.LoadClaimsForToken method WSO2 always reponds with active=false, it expects "token_type_hint=bearer" or nothing.

**Proposal**
Add TokenTypeHint to the OAuth2IntrospectionOptions class so that it optionally can be set in the AddOAuth2Introspection method:

`services.AddAuthentication("Bearer")
    .AddOAuth2Introspection("Bearer", options =>
    {
        options.IntrospectionEndpoint = "...";
        options.ClientId = "...";
        options.ClientSecret = "...";
        options.TokenTypeHint = "...";
    });`

and use this value in the OAuth2IntrospectionHandler.LoadClaimsForToken method

`return await introspectionClient.SendAsync(new IntrospectionRequest
{
    Token = token,
    TokenTypeHint = Options.TokenTypeHint,
    ClientId = Options.ClientId,
    ClientSecret = Options.ClientSecret
}).ConfigureAwait(false);`

**Comment by mikaelstrid** [comment]
I have created a pull request with a proposed solution, #31 .

**Comment by leastprivilege** [comment]
Sorry - going through my backlog.

`token_type_hint=bearer` is not even a legal token type according to the spec...

Have you told WSO2?

**Comment by mikaelstrid** [comment]
Yeah I know, and this is not first occasion where WSO2 not following the spec is causing us problems.

Unfortunately the company I work for is large and have "official channels" to its suppliers so it will take som time getting through with the issue report to WSO2, so I thought changing the token_type_hint to optional/configurable in the IdentityModel.AspNetCore.OAuth2Introspection library was a quicker solution. :)

**Comment by leastprivilege** [comment]
OK - merged.
