### ISSUE TITLE
Add the ability to intercept AuthenticationTicket creation

### ISSUE THREAD

**Issue by Jarga** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#33]
To mirror implementations of the other authentication middleware implementations which allow you to intercept ticket creation and potentially add your own claims or record user information.

  The events implementation in the AuthenticationHandler object provides an easy hook into authentication handler events that facilitates a useful pattern of hydrating claims or other principal information as part of the handler itself.

I created a PR with the implementation for intercepting AuthenticationTicket creation. #32

**Comment by leastprivilege** [comment]
pushed a new nuget. thanks!
