### ISSUE TITLE
DiscoveryClient HTTPS required

### ISSUE THREAD

**Issue by MontyGvMC** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#39]
Reading [the Discovery Client docs](https://identitymodel.readthedocs.io/en/latest/client/discovery.html#discovery-policy) it reveals that it has a discovery policy that enforces HTTPS for non localhost addresses.

I haven't found a way to disable that.

Is there a way to disable the enforcement of HTTPS for non localhosts?

Currently I am getting the error message:
`Error connecting to http://xxx/.well-known/openid-configuration: HTTPS required`

Since all other clients (Angular, Swagger, some hardware clients) are able to connect to the IdentityServer4 TokenService I assume this is error is thrown from the IdentityModel client library?

**Comment by leastprivilege** [comment]
How do you configure the handler right now?

**Comment by MontyGvMC** [comment]
Which hander? Client or server side?

All the code I use for the "client" is posted above.
Could you please tell me if this is a client/service side problem or a problem of the settings on the receiving API causing the HTTPS required error?


The server side configuration is nearly exactly like the code[ in this StackOverflow question](https://stackoverflow.com/questions/52930385/identity-server-4-client-credentials-for-custom-endpoint-on-token-server) + the additional setting RequireHttpsMetadata to false for the custom authentication scheme. 
The example service calls the endpoint1.

**Comment by MontyGvMC** [comment]
Just for those who stumple accross this too. The solution is simple.
Instead of using the static method with the default policy like in the samples:

```
var discoveryResponse = await DiscoveryClient.GetAsync(_options.AuthorizationEndpoint);
```

Create a new instance first. This lets us access the policy and it can be modified.

```
DiscoveryClient discoveryClient = new DiscoveryClient(_settings.AuthorizationEndpoint);
discoveryClient.Policy.RequireHttps = false;
```

**Comment by moedeveloper** [comment]
but by this you are disabling https :( there should be a solution for  that :(
