### ISSUE TITLE
Long-living reference token support

### ISSUE THREAD

**Issue by instantsc** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#41]
At the time, SetClaimsAsync in https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/dev/src/Infrastructure/CacheExtensions.cs makes a call to int.Parse, which makes for an awkward overflow for long-living reference tokens, leading to them having an expiration date in the past, and, subsequently, them not being cached. 
I believe that if you could change this to `long.Parse` (and add `long` version of extension method for `ToDateTimeOffsetFromEpoch`, which only requires changing the argument type), this problem would be solved.

As it is, to solve this little issue of tokens not caching in our project, we have to fork both this and token validation repos for a one-line change, which is a pity.

**Comment by leastprivilege** [comment]
Thanks - we will look into it.

**Comment by leastprivilege** [comment]
Do you want to PR?

You could use 

https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.fromunixtimeseconds?view=netframework-4.7.2

and

https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.tounixtimeseconds?view=netframework-4.7.2

instead.

**Comment by instantsc** [comment]
Checked the file, and it appears that https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/commit/031a53296a62fea44b91f1f355fc30cf539e51bd#diff-d138c68b1dbd85b0cfd2b2b8be1a0722 fixed it.
 Sorry I never got to doing a PR myself, but nevertheless the issue should be resolved now
