### ISSUE TITLE
How to map permissions from the introspection results to scope ?

### ISSUE THREAD

**Issue by madhub** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#42]
Hi 
Current implementation of **IdentityModel.AspNetCore.OAuth2Introspection** works when **IntrospectionResponse** includes **scope** , is their any way to map **permission list** returned in the response to **scope**. **OAUTH2 server** we are using returns the following json response for introspection
If we have to validate our API against these permission, how should we do using the  **IdentityModel.AspNetCore.OAuth2Introspection**library.

IntrospectionResponse from our third party  OAUTH2 server
```json
{
  "active": true,
  "scope": "read write email",
  "client_id": "J8NFmU4tJVgDxKaJFmXTWvaHO",
  "username": "aaronpk",
  "exp": 1437275311,
  "organizations": {
    "managingorganization": "xasass",
    "organizationlist": [
      {
        "organizationid": "cd3c26979bf2",
        "permissions": [
          "read",
          "write"
        ]
      }
    ]
  }
}
```
Is it possible to have option in the **OAuth2IntrospectionOptions** to **retrieve scope** from the **json response**. Default behavior is as is , if developer interested in parsing the json, he can provide function which returns scope from json
```C#
public class OAuth2IntrospectionOptions : AuthenticationSchemeOptions
{
        /// <summary>
        /// Specifies the method how to retrieve the scope from IntrospectionResponse Json string
        /// </summary>
        public Func<string, string> ScopeRetriever { get; set; } 

        /// <summary>
        /// Specifies the method how to retrieve the token from the HTTP request
        /// </summary>
        public Func<HttpRequest, string> TokenRetriever { get; set; } = TokenRetrieval.FromAuthorizationHeader();
}
```

**Comment by leastprivilege** [comment]
This is not the job of an authentication handler. 

Use some middleware or claims transformation for that.

**Comment by madhub** [comment]
Thanks for excellent library ,not sure I agree with your reasoning for not adding the option.  
Don't think it has transformation handler, just an option populate the **scope** from the response where default implementation insufficient . 
As you know **introspection response** varies widely between different **implementation of OAUTH2**, it good to have flexibility in the library to support these cases .


I am not sure how to achieve this with events, I will explore  the possibility , other option is to use **IntrospectionHttpHandler** intercept the response .

**Comment by leastprivilege** [comment]
In the event you get passed in the claims principal after introspection - then you can do whatever transformation you want and replace the principal.

**Comment by madhub** [comment]
Thanks  , I was able to use on **OnCreatingTicket** with data from **claims principal** to add additional claims.

Thanks
