### ISSUE TITLE
Dependency on Newtonsoft.JSON 12.0.1

### ISSUE THREAD

**Issue by raghumirajkar** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#43]
Hi,

We are using the pre-release version of IdentityModel.AspNetCore.OAuth2Introspection (4.0.0-aultmore) with ASP.Net Core 2.0. Since we're using Newtonsoft.JSON 11.0, the build for our project fails due to IdentityModel's hard dependency on Newtonsoft.JSON 12.0.1. Is there any specific feature of latest version of newtonsoft that Identity model is using? If not, can the library downgrade the newtonsoft dependency to 11.0?

**Comment by leastprivilege** [comment]
did you do some research on the topic?

**Comment by leastprivilege** [comment]
https://www.nuget.org/packages/IdentityModel.AspNetCore.OAuth2Introspection/4.0.0-preview.6

Here's the latest preview using the same JSON.NET version as ASP.NET Core (which is 11.0.x)
