### ISSUE TITLE
Supporting older version newtonsoft 

### ISSUE THREAD

**Issue by madhub** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#44]
Currently we use feature , which only available in **pre-release(4.0.0-aultmore)** version of OAuth2Introspection  ( **ClientCredentialStyle.AuthorizationHeader**), which in turn requires newtonsoft version 12. 
![image](https://user-images.githubusercontent.com/8907962/55475898-c382e600-5632-11e9-8f0f-ad0cff6a2ea1.png)

In our current project we have standardized on newtonsoft 11.0.1, hence moving to newer version is problematic , with this context , I have couple of questions
- Is it possible to use the library with older version of **newtonsoft 11.0.1** ?
- Is **OAuth2Introspection**  library moved to newer version due to some feature only available new **newtonsoft 12** ?
- If we do assembly redirect to older version , will it work ?

**Comment by leastprivilege** [comment]
did you do some research on the topic?

**Comment by madhub** [comment]
Since I did not see any response from you , we decided to use the older version (3.5) which has older newtonsoft .

**Comment by leastprivilege** [comment]
Yea - well. v12 is now 6 months old. I have to pick one version. Regardless which one I chose, someone will disagree.

**Comment by madhub** [comment]
Yes, I understand  
But some input to consider , if you keep older newtonsoft comparability (11.0.1) , user who wants to move to 12.0 can use ,but not other way.

**Comment by leastprivilege** [comment]
I will use the same version as ASP.NET Core 2.2 uses - which is 11.0.x

**Comment by leastprivilege** [comment]
Here's the latest preview

https://www.nuget.org/packages/IdentityModel.AspNetCore.OAuth2Introspection/4.0.0-preview.6
