### ISSUE TITLE
Probably wrong Log Level Used

### ISSUE THREAD

**Issue by vanthome** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#6]
I did a simple test and stopped IdentityServer4 and let my app running with `app.UseIdentityServerAuthentication(...)`. 
I can then see this log message which is clearly logged with the wrong severity. I think this should be at least `error`. I could not find the code which is emitting this message but I assume it's from IdentityModel.

```
info: IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionMiddleware[7]
      Bearer was not authenticated. Failure message: Error returned from introspection endpoint: An error occurred while sending the request.
```

**Comment by leastprivilege** [comment]
This log message is coming from Microsoft's authentication infrastructure.

We could add additional logging with a higher severity.

**Comment by brockallen** [comment]
fixed
