### ISSUE TITLE
Removing access token from cache

### ISSUE THREAD

**Issue by raghumirajkar** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#64]
Hi,

We have a requirement where the cached access token can be revoked by the OAuth server and send a notification to the subscribers about the revocation on subscription. To cache the token in IdentityModelOAuth2Introspection, we have used AddDistributedMemoryCache() to the service collection and when we receive the revocation notification from the server, we try to remove the cached access token from the memory cache. On the introspection options, we have SaveToken=true and EnableCaching=true.
In ConfigureServices() we use serviceCollection.BuildServiceProvider().GetService<IDistributedCache>() to get the instance of distributed cache added previously to pass this instance to one of our handlers. But the instance retrieved here does not contain the cached token when the handler is invoked. However, if IDistributedCache is injected in the controller, that instance has the cached token added. This is very tricky. Please suggest what is wrong/how to resolve this issue.

FYI NuGet version of IdentityModelOAuth2Introspection - 3.5.0

Regards,
Raghavendra

**Comment by leastprivilege** [comment]
Sorry hard to tell. I can't (don't want) to debug your code.

I guess you need to build an endpoint of some sort that access the cache and remove the entry.
