### ISSUE TITLE
Caching requires IDistributedCache

### ISSUE THREAD

**Issue by gthvidsten** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#66]
If I try to turn on caching in the configuration I get the following error message

> Caching is enabled, but no IDistributedCache is found in the services collection

Here's the configuration:

```csharp
public void ConfigureServices(IServiceCollection services) {
    services.AddAuthentication(OAuth2IntrospectionDefaults.AuthenticationScheme)
        .AddOAuth2Introspection(options => {
            options.Authority = "https://myidentityserver";
            options.ClientId = "myapi";
            options.ClientSecret = "myapisecret";
            options.EnableCaching = true;
        });

    services.AddControllers();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();
    app.UseEndpoints(endpoints => {
        endpoints.MapControllers();
    });
}
```

I don't have my own `IDistributedCache`, so shouldn't there be some default implementation that IdentityModel uses if it doesn't find one in the DI container?

_IdentityModel.AspNetCore.OAuth2Introspection version 4.0.1_

**Comment by leastprivilege** [comment]
`services.AddDistributedMemoryCache();` gives you a in-memory implementation.

**Comment by leastprivilege** [comment]
nope. Been there since a couple of versions.

**Comment by leastprivilege** [comment]
Maybe it is not added by default anymore in 3.

**Comment by gthvidsten** [comment]
It does indeed sound like this is not added by default anymore.

In any case `.AddDistributedMemoryCache()` worked wonders, so thanks for that :)

**Comment by fanc-mso** [comment]
Just for reference, to help anybody else out, as I stumbled upon the same:

In Asp.net Core 2.2 you probably called services.AddMvc() in Startup, which itself adds DistributedMemoryCache implicitely.

In Asp.net Core 3.x, if you call only services.AddControllers(), the memory cache is not added by default. You have to add it explicitely, like calling services.AddDistributedMemoryCache().

Hope that helps
