### ISSUE TITLE
How to also retrieve userinfo?

### ISSUE THREAD

**Issue by gthvidsten** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#68]
I really like how `OAuth2Introspection` automatically performs checks against the `/introspect` endpoint and places claims on the `User`. However, I would also very much like to automatically retrieve data from the `/userinfo` endpoint in the same way (so that just by decorating a method/controller with `[Authorize]` it will also invoke `/userinfo` and place the resulting data in the `User` object)

How can I accomplish this?

**Comment by leastprivilege** [comment]
userinfo is a OpenID Connect concept. It is for clients - not resources.

**Comment by gthvidsten** [comment]
Thanks for the link.

Can the information returned from `/userinfo` be classified as a "User Claim" so that I can add this specific userinfo-claim into my ApiResource, or is there some other limiting factor?

**Comment by leastprivilege** [comment]
No. that's what you can do.

**Comment by gthvidsten** [comment]
I finally got around to test this, and it worked like a charm!
Thanks for the suggestion :D
