### ISSUE TITLE
Error: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions]' from root provider.

### ISSUE THREAD

**Issue by rodneykendall** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#72]
I have a project that is unable to work with the nuget package. I receive the error Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions]' from root provider. Through some searching, I found a thread on the asp net core site that stated IOptionsSnapshot should be replaced with IOptionsMonitor to prevent such scoping issues. Our project is very complex, and the scope of each component is just as complex. I brought the code locally and the scope error I was receiving went away once I changed the TokenEndpointService to use IOptionsMonitor instead of IOptionsSnapshot.

My question is would this change be acceptable for the repository, and if so, could I submit a pull request with the change?

**Comment by leastprivilege** [comment]
Yes please.

**Comment by leastprivilege** [comment]
any progress?

**Comment by rodneykendall** [comment]
Yes, would you please give me access to the IdentityModel.AspNetCore repository to allow me to push the branch? I put this issue on the wrong project, unfortunately.

**Comment by leastprivilege** [comment]
You don't need write access. Simply send a PR.
