### ISSUE TITLE
IntrospectionHttpHandler is removed from OAuth2IntrospectionOptions in v4.0

### ISSUE THREAD

**Issue by shlahni** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#83]
I was using IntrospectionHttpHandler to add a custom header to my oauth2 request.
it seems it's removed in new version and I couldn't find any documentation to help me how to handle this breaking change in version 4.

this was my working code in v3.5 : 
...
options.InterospectionHttpHandler = new CustomHttpHandler() {
InnerHandler = new HttpClientHandler()
};

CustomHttpHandler : DelegtingHttpHandler {
    .. SendAsync(...) {
           request.Headers.Add("key","value")
      }
}

**Comment by leastprivilege** [comment]
I am using the HttpClientFactory now. which is the better approach IMO....

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/master/test/Tests/Util/PipelineFactory.cs#L35-L39
