### ISSUE TITLE
Extra validation options (e.g. Audience)

### ISSUE THREAD

**Issue by wkoeter** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#97]
I Want both validation and introspection at the same time.

For example: 

- using 'introspection' the token is seen as valid even though the client-id is not in the audience.
- using 'JWT validation', the token can be seen as valid even though it is revoked.

I've added a custom authentication handler to do both. Using both `AddJwtBearer` and `AddOAuth2Introspection` in a custom authentication handler decreases performance because it takes 2 trips tot the authorization server.

Is it an idea to extend this package to allow extra JWT validation?

**Comment by leastprivilege** [comment]
> using 'introspection' the token is seen as valid even though the client-id is not in the audience.

The client ID should not be the audience. The API is the audience.

**Comment by wkoeter** [comment]
Okay, fair enough. However, that still means that the audience can be different from my Api and still is seen as valid. Or is there a property/method to use to send/check valid audiences?

**Comment by leastprivilege** [comment]
I don't follow. In introspection the token is valid if the STS returns it as valid. This has nothing to do with the audience.

**Comment by wkoeter** [comment]
Reading between the lines you are telling me that this is not the place for Audience validation. 
Introspection should not be concerned with audience validation.

Since `.AddJwtBearer` and `.AddOAuth2Introspection` do not play nice together because they use the same schema, a workaround solution is needed to check if the token is active and if the audience is valid. It seems that this is not the place to do this.

**Comment by leastprivilege** [comment]
I did something like this here

https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation

or you could use a policy scheme to multiplex between two handlers.

**Comment by wkoeter** [comment]
Thank you for the link, my solution looks similar to what you did with IdentityServer. I'm not using IdentityServer so did not want to any related dependencies in if a solution is housed there.
